version: "3.8"

services:
  db:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=1122
    expose:
      - "5432"
      

  backend:
    build: ./django_proj
    volumes:
      - ./django_proj:/app/backend
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    command: sh -c "cd proj && python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  # frontend:
  #   build: ./frontend
  #   volumes:
  #     - ./frontend:/app/frontend
  #     # One-way volume to use node_modules from inside image
  #     - /app/frontend/node_modules
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=development
  #   depends_on:
  #     - backend
  #   command: npm start
  